### ISSUE TITLE
Not working with latest Vue CLI 

### ISSUE THREAD

**Issue by paulwaldmann** [pascalvgemert/vue-instant-page#1]
## main.js
```
import Vue from 'vue'
import App from './App.vue'
import router from './router'

import VueInstantPage from 'vue-instant-page'
Vue.use(VueInstantPage)

new Vue({
  router,
  render: (h) => h(App)
}).$mount('#app')
```

## error.log
``` 
error in ./node_modules/vue-instant-page/dist/vue-instant-page.min.js

Module parse failed: Unexpected token (1:21)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders        
> TypeError: promisify is not a function
|     at Object.<anonymous> (/Users/pascalvangemert/Development/Ironman/Vue-Instant-Page/node_modules/minify/lib/minify.js:10:18)
|     at Module._compile (module.js:571:32)

 @ ./src/main.js 8:0-46 9:8-22
 @ multi (webpack)-dev-server/client?http://192.168.107.41:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by pieterjandesmedt** [comment]
@paulwaldmann, did you get it to work? If so, how?

**Comment by paulwaldmann** [comment]
> @paulwaldmann, did you get it to work? If so, how?

Hey @pieterjandesmedt, apologies for the delayed response, totally missed that email.

Just import it locally, works like a charm.

![Capture](https://user-images.githubusercontent.com/32001342/101053815-81891080-3588-11eb-9cf7-d28195d97473.PNG)
